// Generated by GasaGen/GasaGen_UGasaAttributeSet.cpp
#pragma once

#include "GasaAttributeSet.h"
#include "AbilitySystemComponent.h"

FORCEINLINE
void UGasaAttributeSet::SetHealth( float NewVal )
{
	UAbilitySystemComponent* AbilityComp = GetOwningAbilitySystemComponent();
	if ( ensure( AbilityComp ) )
	{
		AbilityComp->SetNumericAttributeBase( GetHealthAttribute(), NewVal );
	};
}
FORCEINLINE
void UGasaAttributeSet::SetMaxHealth( float NewVal )
{
	UAbilitySystemComponent* AbilityComp = GetOwningAbilitySystemComponent();
	if ( ensure( AbilityComp ) )
	{
		AbilityComp->SetNumericAttributeBase( GetMaxHealthAttribute(), NewVal );
	};
}
FORCEINLINE
void UGasaAttributeSet::SetMana( float NewVal )
{
	UAbilitySystemComponent* AbilityComp = GetOwningAbilitySystemComponent();
	if ( ensure( AbilityComp ) )
	{
		AbilityComp->SetNumericAttributeBase( GetManaAttribute(), NewVal );
	};
}
FORCEINLINE
void UGasaAttributeSet::SetMaxMana( float NewVal )
{
	UAbilitySystemComponent* AbilityComp = GetOwningAbilitySystemComponent();
	if ( ensure( AbilityComp ) )
	{
		AbilityComp->SetNumericAttributeBase( GetMaxManaAttribute(), NewVal );
	};
}

namespace Gasa
{
	inline UGasaAttributeSet const* GetAttributeSet( UAbilitySystemComponent* ASC )
	{
		return Cast<UGasaAttributeSet>( ASC->GetAttributeSet( UGasaAttributeSet::StaticClass() ) );
	}

}
