// This was generated by GasaGen/GasaGen.cpp
#include "GasaDevOptionsCache.h"

#include "GasaDevOptions.h"
#include "Actors/CameraMount.h"
#include "UI/UI_HostWidget.h"
using namespace Gasa;

void FGasaDevOptionsCache::CachedDevOptions()
{
	UGasaDevOptions* DevOpts = GetMutDevOptions();

	Template_PlayerCamera = DevOpts->Template_PlayerCamera.LoadSynchronous();
	Template_HUD_HostUI   = DevOpts->Template_HUD_HostUI.LoadSynchronous();

	Tag_GlobalPPV = DevOpts->Tag_GlobalPPV;
}
