// This was generated by GasaGen/GasaGen.cpp
#pragma once

#include "GasaDevOptionsCache.generated.h"

USTRUCT()
struct GASA_API FGasaDevOptionsCache
{
	GENERATED_BODY()

	UPROPERTY()
	UClass* Template_PlayerCamera;
	UPROPERTY()
	UClass* Template_HUD_HostUI;

	void CachedDevOptions();
};
